// Automatically generated by MockGen. DO NOT EDIT!
// Source: netlinkWrapper/netlink.go

package mock_netlinkWrapper

import (
	gomock "github.com/golang/mock/gomock"
	netlink "github.com/vishvananda/netlink"
)

// Mock of NetLink interface
type MockNetLink struct {
	ctrl     *gomock.Controller
	recorder *_MockNetLinkRecorder
}

// Recorder for MockNetLink (not exported)
type _MockNetLinkRecorder struct {
	mock *MockNetLink
}

func NewMockNetLink(ctrl *gomock.Controller) *MockNetLink {
	mock := &MockNetLink{ctrl: ctrl}
	mock.recorder = &_MockNetLinkRecorder{mock}
	return mock
}

func (_m *MockNetLink) EXPECT() *_MockNetLinkRecorder {
	return _m.recorder
}

func (_m *MockNetLink) LinkByName(name string) (netlink.Link, error) {
	ret := _m.ctrl.Call(_m, "LinkByName", name)
	ret0, _ := ret[0].(netlink.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockNetLinkRecorder) LinkByName(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LinkByName", arg0)
}

func (_m *MockNetLink) LinkList() ([]netlink.Link, error) {
	ret := _m.ctrl.Call(_m, "LinkList")
	ret0, _ := ret[0].([]netlink.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockNetLinkRecorder) LinkList() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LinkList")
}
