// Copyright 2015-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/aws/amazon-ecs-agent/agent/resources/platformResources (interfaces: PlatformResources)

package mock_platformResources

import (
	api "github.com/aws/amazon-ecs-agent/agent/api"
	gomock "github.com/golang/mock/gomock"
)

// Mock of PlatformResources interface
type MockPlatformResources struct {
	ctrl     *gomock.Controller
	recorder *_MockPlatformResourcesRecorder
}

// Recorder for MockPlatformResources (not exported)
type _MockPlatformResourcesRecorder struct {
	mock *MockPlatformResources
}

func NewMockPlatformResources(ctrl *gomock.Controller) *MockPlatformResources {
	mock := &MockPlatformResources{ctrl: ctrl}
	mock.recorder = &_MockPlatformResourcesRecorder{mock}
	return mock
}

func (_m *MockPlatformResources) EXPECT() *_MockPlatformResourcesRecorder {
	return _m.recorder
}

func (_m *MockPlatformResources) Cleanup(_param0 *api.Task) error {
	ret := _m.ctrl.Call(_m, "Cleanup", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockPlatformResourcesRecorder) Cleanup(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Cleanup", arg0)
}

func (_m *MockPlatformResources) Setup(_param0 *api.Task) error {
	ret := _m.ctrl.Call(_m, "Setup", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockPlatformResourcesRecorder) Setup(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Setup", arg0)
}
